export const eventCategories = [
  'Alpine skiing',
  'American football',
  'Archery',
  'Badminton',
  'Baseball',
  'Basketball',
  'Beach volleyball',
  'Billiard',
  'BMX',
  'Bouldering',
  'Canoeing',
  'Cricket',
  'Cross country skiing',
  'Cycling',
  'Dancing',
  'Dodgeball',
  'Field hockey',
  'Fishing',
  'Floorball',
  'Foosball',
  'Football',
  'Frisbee',
  'Golf',
  'Handball',
  'Hiking',
  'Horse riding',
  'Ice hockey',
  'Ice skating',
  'Kayaking',
  'Mountain biking',
  'Paddleboarding',
  'Padel',
  'Paintball',
  'Parkour',
  'Pool',
  'Rafting',
  'Rugby',
  'Running',
  'Sailing',
  'Scootering',
  'Skateboarding',
  'Snooker',
  'Snowboarding',
  'Squash',
  'Surfing',
  'Table tennis',
  'Tennis',
  'Volleyball',
  'Waterpolo'
]
